In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [5]:
import numpy as np
import pandas as pd

np.random.seed(23) 

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = pd.concat( [df, df1],ignore_index=True)

In [6]:
df = df.sample(40)

In [12]:
df.head(5)

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [16]:
#Step - 1 ; Apply Standardization (mean Centric)

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

df.iloc[:,0:3] = ss.fit_transform(df.iloc[:,0:3])

In [19]:
#Step - 2 ; find COVARIANCE matrix

covariance_matrix = np.cov( [df.iloc[:,0], df.iloc[:,1], df.iloc[:,2] ])
print(covariance_matrix)

[[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [20]:
# Step - 3 ; find eigen vector and eigen values

eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [21]:
eigen_values, eigen_vectors

(array([1.3536065 , 0.94557084, 0.77774573]),
 array([[-0.53875915, -0.69363291,  0.47813384],
        [-0.65608325, -0.01057596, -0.75461442],
        [-0.52848211,  0.72025103,  0.44938304]]))

In [22]:
np.cumsum(eigen_values)

array([1.3536065 , 2.29917734, 3.07692308])

In [23]:
pc = eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [24]:
transformed_df = np.dot(df.iloc[:,0:3], pc.T)

In [27]:
transformed_df.shape

(40, 2)

In [29]:
new_df = pd.DataFrame(transformed_df, columns = ['PC1', 'PC2'])
new_df['target'] = df.iloc[:,-1]

In [32]:
new_df

PC1       PC2 target
0   0.599433  1.795862      1
1   1.056919 -0.212737      1
2  -0.271876  0.498222      1
3  -0.621586  0.023110      1
4   1.567286  1.730967      1
5  -1.320157 -0.257002      1
6  -0.470834 -1.373121      1
7  -0.401542  1.203061      1
8  -0.433734  1.153326      1
9   0.227326 -2.669841      1
10  1.007007  0.596022      1
11  1.726114  0.492511      1
12 -0.429384  0.829265      1
13  0.886733  0.522664      1
14 -0.872205  0.530675      1
15 -3.367715 -0.254627      1
16  0.688605  0.658084      1
17 -0.478444  0.774372      1
18  1.304549  0.476645      1
19 -0.729043 -0.846506      1
20 -0.069178 -0.130994      0
21  0.484802 -1.217708      0
22  1.058221 -0.452026      0
23  0.741715  1.023822      0
24  0.202775  0.091815      0
25 -0.757890 -2.422615      0
26 -0.138331 -0.368372      0
27 -0.220797 -1.441911      0
28 -1.124520  0.842226      0
29 -0.434777 -0.603836      0
30  0.232113 -1.153250      0
31  1.464336 -1.510939      0
32 -1.348823 -0.536119      0
33 -0.278732 -0.447581      0
34  1.631677  1.894527      0
35 -0.144559  0.494895      0
36  0.623953  0.088371      0
37 -0.997408  0.778938      0
38 -0.497476  0.161370      0
39 -0.094556 -0.761566      0